name: BuildAndTest

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
         
jobs:
  build:
    strategy:
          matrix:
            Assignment: [1, 2, 3, 4, 5]
            Config: [Debug, Release]
    
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
        
    - name: Run MSBuild
      working-directory: ./Assignment${{ matrix.Assignment }}/CompilerClassAssignment${{ matrix.Assignment }}
      run: msbuild.exe CompilerClassAssignment${{ matrix.Assignment }}.sln -p:Configuration=${{ matrix.Config }}
        
    - name: Run Project
      working-directory: ./Assignment${{ matrix.Assignment }}
      run: CompilerClassAssignment${{ matrix.Assignment }}/${{ matrix.Config }}/CompilerClassAssignment${{ matrix.Assignment }}.exe > Out.txt
      
    - name: Archive Output
      if: always()
      uses: actions/upload-artifact@v2
      with:
        path: ./Assignment${{ matrix.Assignment }}/Out.txt
        
    - name: Run Reference
      working-directory: ./Assignment${{ matrix.Assignment }}
      run: Reference/CompilerClassAssignment${{ matrix.Assignment }}.exe > Ref.txt

    - name: File Diff
      # You may pin to the exact commit or the version.
      # uses: tianhaoz95-actions/file-diff@02328b477669ac73288aa4a069c8ace6a6cf967c
      uses: tianhaoz95-actions/file-diff@v1.0.0
      with:
        # The LHS file to compare
        lhs: ./Assignment${{ matrix.Assignment }}/Ref.txt
        # The RHS file to compare
        rhs: ./Assignment${{ matrix.Assignment }}/Out.txt
